repos:
  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.1.0
    hooks:
      - id: seed-isort-config
        args: [--exclude=tests/.*\.py]
        language_version: python3.7
  - repo: https://github.com/timothycrosley/isort
    rev: 4.3.21
    hooks:
      - id: isort
        language_version: python3.7
  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
      - id: black
        language_version: python3.7
#  - repo: https://github.com/PyCQA/flake8
#    rev: 3.7.9
#    hooks:
#      - id: flake8
