version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: "%(message)s"
    complete:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
    console_handler:
        class: logging.StreamHandler
        formatter: simple
        level: INFO
        stream: ext://sys.stdout

    debug_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: complete
        filename: debug.log # Prepended with correct directory in application code
        maxBytes: 20971520 # 20MB
        backupCount: 20
        encoding: utf8

    info_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: complete
        filename: info.log # Prepended with correct directory in application code
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: complete
        filename: errors.log # Prepended with correct directory in application code
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

loggers:
    meeshkan:
        level: DEBUG

root:
    handlers:
        [
            console_handler,
            debug_file_handler,
            info_file_handler,
            error_file_handler,
        ]
